import { useMemo, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { Alert } from '../components/Alert'
import { Confidence } from '../components/Confidence'
import { submitReview } from '../services/api'
import { readWorkflow } from '../services/workflow'

const num = (value?: number) => Number(value || 0)
export function ReviewPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const manual = params.get('manual') === '1'; const { assessment, answer, job } = readWorkflow(); const correction = job?.latest_execution
  const question = assessment?.question || assessment?.questions?.[0]; const rubric = question?.rubric?.criteria || []
  const nameFor = (criterionId: string, index: number) => rubric.find(c => c.id === criterionId)?.name || `Critério ${index + 1}`
  const suggestions = correction?.criterion_scores || rubric.map(c => ({ criterion_id: c.id || c.name, max_score: c.max_score, score: 0, evidence: undefined as string | undefined, reason: undefined as string | undefined, confidence: undefined as number | undefined }))
  const [mode, setMode] = useState<'view' | 'alter'>(manual ? 'alter' : 'view'); const [scores, setScores] = useState<Record<string, number>>(() => Object.fromEntries(suggestions.map(s => [s.criterion_id, num(s.score)])))
  const [justification, setJustification] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const total = useMemo(() => Object.values(scores).reduce((a, b) => a + num(b), 0), [scores]); const suggestedTotal = suggestions.reduce((a, b) => a + num(b.score), 0)
  const validScores = suggestions.every(s => scores[s.criterion_id] >= 0 && scores[s.criterion_id] <= s.max_score); const canAlter = validScores && Boolean(justification.trim())
  const send = async (decision: 'APPROVE' | 'ALTER') => { const jobId = job?.id; if (!jobId) { setError('O servidor não forneceu o identificador da correção. Não é possível registrar a decisão.'); return } setBusy(true); setError(''); try { await submitReview(jobId, decision === 'APPROVE' ? { decision } : { decision, criteria_scores: suggestions.map(s => ({ criterion_id: s.criterion_id, score: scores[s.criterion_id] })), justification: justification.trim() }); navigate('/avaliacoes', { state: { reviewSaved: true } }) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível registrar sua decisão.') } finally { setBusy(false) } }
  if (!question || !answer) return <Alert>Os dados da revisão não estão disponíveis nesta sessão. <Link to="/avaliacoes">Volte às avaliações</Link> e abra a resposta novamente.</Alert>
  return <><div className="page-heading"><div><p className="eyebrow">Revisão humana obrigatória</p><h1>Revise antes de confirmar</h1><p>A sugestão apoia sua análise. A decisão final é sempre sua.</p></div></div>
    {correction?.engine_mode === 'simulated' && <Alert type="warning"><strong>Análise em modo simulado.</strong> Este resultado não foi gerado pelo modelo real e deve ser usado apenas para demonstração. Faça a revisão manual completa.</Alert>}
    {manual && <Alert type="warning"><strong>Modo de correção manual.</strong> A IA não produziu uma sugestão. Preencha a pontuação de cada critério.</Alert>}{error && <Alert>{error}</Alert>}
    <div className="review-layout"><section className="panel review-source"><span className="label">Enunciado</span><h2>{question.statement}</h2><div className="answer-box"><span className="label">Resposta do aluno — somente leitura</span><p>{answer.text}</p></div></section>
      <section className="review-criteria" aria-label="Critérios de correção">{suggestions.map((item, index) => <article className="criterion-review" key={item.criterion_id}><div className="criterion-title"><div><span className="label">Critério {index + 1}</span><h2>{nameFor(item.criterion_id, index)}</h2></div><strong>{mode === 'alter' ? <><input className="score-input" aria-label={`Pontuação para ${nameFor(item.criterion_id, index)}`} type="number" min="0" max={item.max_score} step="0.1" value={scores[item.criterion_id]} onChange={e => setScores(s => ({ ...s, [item.criterion_id]: Number(e.target.value) }))} /> / {item.max_score}</> : <>{item.score} / {item.max_score}</>}</strong></div>
        {!manual && <div className="ai-suggestion"><span className="ai-label">Sugestão da IA — revisar</span><p><strong>Evidência:</strong> {item.evidence || 'Nenhum trecho foi informado.'}</p><p><strong>Justificativa:</strong> {item.reason || 'Justificativa não informada.'}</p><Confidence value={item.confidence} /></div>}{mode === 'alter' && (scores[item.criterion_id] < 0 || scores[item.criterion_id] > item.max_score) && <small className="field-error">Use um valor entre 0 e {item.max_score}.</small>}</article>)}</section></div>
    <section className="decision-bar"><div className="ai-total"><span>Sugestão da IA — revisar</span><strong>{manual ? 'Não disponível' : `${suggestedTotal.toLocaleString('pt-BR')} pontos`}</strong>{!manual && <Confidence value={correction?.overall_confidence} />}{correction?.confidence_method_version && <small>Método: {correction.confidence_method_version}</small>}{correction?.flags?.length ? <p><strong>Pontos de atenção:</strong> {correction.flags.join(' • ')}</p> : null}</div>
      <div className="human-decision"><span>Decisão humana</span>{mode === 'alter' ? <><strong>Nota final a confirmar: {total.toLocaleString('pt-BR')} pontos</strong>{!manual && Math.abs(total - suggestedTotal) > 0.001 && <p className="divergence">Diferença em relação à sugestão da IA: {(total - suggestedTotal).toLocaleString('pt-BR', { signDisplay: 'always' })} ponto(s).</p>}<label>Justificativa da alteração<textarea rows={3} required value={justification} onChange={e => setJustification(e.target.value)} placeholder="Explique por que a decisão humana difere ou como a nota foi definida" /></label><div className="button-row"><button className="button button--ghost" onClick={() => setMode('view')} disabled={busy || manual}>Cancelar alteração</button><button className="button button--primary" disabled={!canAlter || busy} onClick={() => void send('ALTER')}>{busy ? 'Confirmando…' : 'Confirmar alteração'}</button></div></> : <div className="button-row"><button className="button button--secondary" onClick={() => setMode('alter')}>Alterar sugestão</button><button className="button button--primary" disabled={busy} onClick={() => void send('APPROVE')}>{busy ? 'Confirmando…' : 'Aprovar como decisão humana'}</button></div>}</div>
    </section></>
}
